Algoritmo "Operadores aritméticos"

// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/09/2020
Var
// Seção de Declarações das variáveis 
  resultado, valor01, valor02, valor03: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   valor01 := 10
   valor02 := 10
   valor03 := 10
   resultado := (valor01 + valor02) * valor03
   escreval("Resultado: ", resultado)


Fimalgoritmo