Algoritmo "Operadores relacionais"

// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/09/2020
Var
// Seção de Declarações das variáveis 
  nota01, nota02: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   nota01 := 10
   nota02 := 15

   se (nota01 <> nota02) entao
       escreval("Nota01 é diferente")
   senao
        escreval("Nota é igual")
   fimse

Fimalgoritmo